### ISSUE TITLE
Incorrect Argument in kpi-calculation.ipynb  

### ISSUE THREAD

**Issue by tomsnowgb** [mindsphere/analytics-examples#5]
In kpi-calculation.ipynb  on `In [10]` I suggest you change `--target kpistatus`  to `--target state` so it refers to the `compressor-states.json` column.  

I also suggest an improvement to the documentation to make clear what target variable refers to. If you agree this is an issue I will happily write a pull request.  

Tom ❤

**Comment by sn0wcat** [comment]
Hi @tomsnowgb  Thanks for spotting that :)  I will gladly accept a pull-request :)
